from app.Routes.create_one import *
from app.Routes.CreateAccount import *
from app.Routes.delete_one import *
from app.Routes.DeleteAccount import *
from app.Routes.get_all import *
from app.Routes.GetAllAccount import *
from app.Routes.HomePage import *
from app.Routes.LoginAdmin import *
from app.Routes.Logout import *
from app.Routes.update_one import *
from app.Routes.UpdateAccount import *
